Fix for apps

diff --git a/.github/workflows/nodejs-nx.yaml b/.github/workflows/nodejs-nx.yaml
--- a/.github/workflows/nodejs-nx.yaml
+++ b/.github/workflows/nodejs-nx.yaml
@@ -83,8 +83,8 @@ jobs:
         run: |
               output="$(npm run affected:app 2>&1)"
               echo "Found: $output"
-              echo "Grepping for \${{ inputs.SERVICE_NAME }}"
-              echo "$output" | grep -q \${{ inputs.SERVICE_NAME }} || echo "::notice::Not Found" && echo "RUN='false'" >> $GITHUB_OUTPUT && exit 0
+              echo "Grepping for ${{ inputs.SERVICE_NAME }}"
+              echo "$output" | grep -q ${{ inputs.SERVICE_NAME }} || echo "::notice::Not Found" && echo "RUN='false'" >> $GITHUB_OUTPUT && exit 0
 
       - name: Build app ${{ inputs.SERVICE_NAME }}
         if: steps.apps.outputs.RUN == 'true'
